package com.Inamhi.Inamhi.entidad;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

import java.time.LocalDate;

@Data
@Entity
public class Persona {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer numCodigo;
    private String codigo;
    private String nombreDelFuncionario;
    private String direccion;
    private String email;
    private String tipoRegistro;
    private LocalDate fecha;
    private String tipoEquipo;
    private String sistemaOperativo;
    private String procesador;
    private String tipoDisco;
    private String ram;
    private String capacidadDisco;
    private String discoDuro1;
    private String discoDuro2;
    private String discoDuro3;
    private String discoDuro4;
    private String discoDuro5;
    private String case1;
    private String case2;
    private String case3;
    private String case4;
    private String case5;
    private String monitor1;
    private String monitor2;
    private String monitor3;
    private String monitor4;
    private String monitor5;
    private String teclado1;
    private String teclado2;
    private String teclado3;
    private String teclado4;
    private String teclado5;
    private String maouse1;
    private String maouse2;
    private String maouse3;
    private String maouse4;
    private String maouse5;
    private String ups1;
    private String ups2;
    private String ups3;
    private String ups4;
    private String ups5;
    private String parlantes1;
    private String parlantes2;
    private String parlantes3;
    private String parlantes4;
    private String parlantes5;
    private String memoriaRam1;
    private String memoriaRam2;
    private String memoriaRam3;
    private String memoriaRam4;
    private String memoriaRam5;
    private String camara1;
    private String camara2;
    private String camara3;
    private String camara4;
    private String camara5;
    private String bateria1;
    private String bateria2;
    private String bateria3;
    private String bateria4;
    private String bateria5;
    private String cargadorPortatil1;
    private String cargadorPortatil2;
    private String cargadorPortatil3;
    private String cargadorPortatil4;
    private String cargadorPortatil5;
    private String microfono1;
    private String microfono2;
    private String microfono3;
    private String microfono4;
    private String microfono5;
    private String tarjetaRed1;
    private String tarjetaRed2;
    private String tarjetaRed3;
    private String tarjetaRed4;
    private String tarjetaRed5;
    private String funcionaCorrectamente1;
    private String funcionaCorrectamente2;
    private String funcionaCorrectamente3;
    private String funcionaCorrectamente4;
    private String funcionaCorrectamente5;
    private String observaciones1;
    private String observaciones2;
    private String observaciones3;
    private String observaciones4;
    private String observaciones5;
    private String funcionaCorrectamente11;
    private String funcionaCorrectamente12;
    private String funcionaCorrectamente13;
    private String funcionaCorrectamente14;
    private String funcionaCorrectamente15;
    private String observaciones11;
    private String observaciones12;
    private String observaciones13;
    private String observaciones14;
    private String observaciones15;
    private String mentenimiento;
    private String revisado;
    private String recibido;
    private String cargo1;
    private String cargo2;
}
